---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
stringData:
  # Required for statically and dynamically provisioned volumes
  # The userID must not include the "client." prefix!
  userID: <plaintext ID>
  userKey: <Ceph auth key corresponding to ID above>

  # Encryption passphrase
  encryptionPassphrase: test_passphrase
