---
name: 'Dependency Review'
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'


permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: 'Dependency Review'
        # yamllint disable-line rule:line-length
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019  # v4.5.0
        with:
          allow-ghsas: GHSA-f4w6-3rh6-6q4q
