---
name: test-retest-action
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [devel]
    paths:
      - 'actions/retest/**'
      - '.github/workflows/test-retest-action.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Docker build
        # Run cd to avoid loading complete cephcsi directory in docker context
        # while building retest image.
        run: cd actions/retest && docker build -t retest .
