---
name: List TODO's
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - devel

permissions:
  contents: read

jobs:
  tickgit:
    name: tickgit
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - run: make containerized-test TARGET=tickgit
